/**
 * MaxClean — Internacionalização
 * Suporte: Português (PT), English (EN), Español (ES)
 */

export type Language = 'pt' | 'en' | 'es';

export const strings = {
  pt: {
    // Tab bar
    tabHome: 'Início',
    tabTools: 'Ferramentas',
    tabDiscover: 'Descobrir',
    tabProfile: 'Eu',

    // Home
    appName: 'MaxClean',
    junkFound: 'LIXO ENCONTRADO',
    scanComplete: 'Escaneamento concluído',
    scanning: 'Escaneando...',
    quickClean: 'LIMPEZA RÁPIDA',
    storage: 'Armazenamento',
    ram: 'RAM',
    temperature: 'Temperatura',
    battery: 'Bateria',
    cpu: 'CPU',
    tools: 'Ferramentas',
    seeAll: 'Ver todas',
    free: 'Livre',
    used: 'Usado',
    total: 'Total',
    remaining: 'Restante',
    scanNow: 'Escanear Agora',
    lastScan: 'Último scan',
    never: 'Nunca',

    // Smart Clean
    smartClean: 'Limpeza Inteligente',
    totalFound: 'Total encontrado',
    selected: 'Selecionado',
    itemsToClean: 'Itens para limpar',
    junkCache: 'Cache inútil',
    tempFiles: 'Arquivos temporários',
    oldLogs: 'Logs antigos',
    appResiduals: 'Resíduos de apps',
    thumbnails: 'Miniaturas',
    emptyFolders: 'Pastas vazias',
    oldApks: 'APK antigos',
    uselessDownloads: 'Downloads inúteis',
    cleanBtn: 'LIMPAR',
    cleanConfirm: 'Confirmar Limpeza',
    cleanConfirmMsg: 'Deseja apagar os itens selecionados? Esta ação não pode ser desfeita.',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    cleaning: 'Limpando...',
    cleanDone: 'Limpeza Concluída!',
    spaceFreed: 'Espaço liberado',
    filesRemoved: 'Arquivos removidos',
    timeTaken: 'Tempo gasto',
    seconds: 's',

    // App Clean
    appClean: 'Limpeza de Apps',
    all: 'Todos',
    recommended: 'Recomendado',
    large: 'Grandes',
    socialNets: 'Redes Sociais',
    cleanApp: 'Limpar cache e arquivos temporários',
    openSettings: 'Abrir Configurações do App',
    openSettingsNote: 'O Android restringe a limpeza de cache de outros apps. Toque para abrir as configurações do app e limpar manualmente.',
    appCleanBtn: 'LIMPAR',

    // Duplicates
    duplicates: 'Duplicados',
    photos: 'Fotos',
    videos: 'Vídeos',
    music: 'Músicas',
    docs: 'Documentos',
    others: 'Outros',
    duplicatesFound: 'Duplicados encontrados',
    remove: 'REMOVER',

    // Large Files
    largeFiles: 'Arquivos Grandes',
    above: 'Acima de',
    deleteSelected: 'Apagar Selecionados',

    // Downloads
    downloads: 'Downloads',
    apks: 'APK',
    zips: 'ZIP',
    pdfs: 'PDF',
    neverUsed: 'Nunca utilizados',

    // Empty Folders
    emptyFoldersTitle: 'Pastas Vazias',
    foldersFound: 'pastas vazias encontradas',
    deleteAll: 'APAGAR TUDO',
    totalSize: 'Tamanho total',
    items: 'itens',

    // APK Scanner
    apkScanner: 'Scanner de APK',
    version: 'Versão',
    date: 'Data',
    location: 'Local',
    invalid: 'Inválido',
    duplicate: 'Duplicado',

    // Monitor
    monitor: 'Monitor do Sistema',
    heaviestApps: 'Apps mais pesados',
    memUsage: 'Uso de memória',
    cpuUsage: 'Uso de CPU',
    battRemaining: 'Bateria restante',

    // Hibernate
    hibernate: 'Hibernar Apps',
    background: 'Segundo plano',
    autoStart: 'Início automático',
    consumingResources: 'apps estão consumindo recursos',
    blockSave: 'Bloquear para economizar bateria e RAM',
    hibernateBtn: 'HIBERNAR',
    highCpu: 'Alto consumo de CPU',
    highRam: 'Alto consumo de RAM',
    highBattery: 'Alto consumo de bateria',
    runningBg: 'Execução em segundo plano',

    // History
    history: 'Histórico de Limpezas',
    noHistory: 'Nenhuma limpeza realizada ainda',
    noHistoryDesc: 'Realize uma limpeza para ver o histórico aqui',

    // Settings
    settings: 'Configurações',
    appearance: 'Aparência',
    darkMode: 'Modo Escuro',
    language: 'Idioma',
    autoClean: 'Limpeza Automática',
    schedule: 'Agendamento',
    daily: 'Diária',
    weekly: 'Semanal',
    monthly: 'Mensal',
    notifications: 'Notificações',
    enableNotifications: 'Ativar Notificações',
    trashDays: 'Apagar lixeira após',
    days7: '7 dias',
    days15: '15 dias',
    days30: '30 dias',
    about: 'Sobre',
    privacy: 'Política de Privacidade',
    terms: 'Termos de Uso',
    share: 'Compartilhar App',
    rate: 'Avaliar no Store',
    clearHistory: 'Limpar Histórico',
    resetSettings: 'Restaurar Configurações',
    safeDelete: 'Exclusão Segura',
    safeDeleteDesc: 'Sobrescrever arquivos antes de excluir',

    // Permissions
    permTitle: 'Permissão Necessária',
    permStorage: 'O MaxClean precisa de acesso ao armazenamento para escanear e limpar arquivos.',
    permGrant: 'Conceder Permissão',
    permDenied: 'Permissão negada. Acesse as configurações para ativar.',

    // Errors
    errorScan: 'Erro ao escanear. Verifique as permissões.',
    errorDelete: 'Erro ao excluir arquivo.',
    noFiles: 'Nenhum arquivo encontrado',
    noFilesDesc: 'Seu dispositivo está limpo!',

    // Android limitation notes
    limitationTitle: 'Limitação do Android',
    limitationCache: 'O Android 6+ não permite que apps limpem o cache de outros apps diretamente. Abriremos as configurações para você limpar manualmente.',
    limitationSystem: 'Arquivos do sistema não podem ser acessados sem permissões especiais.',

    // Additional UI strings
    chargeStatus: 'Carregando',
    cpuTempLabel: 'Temperatura da CPU',
    zipFiles: 'Arquivos ZIP',
    deselectAll: 'Desselecionar todos',
    selectAll: 'Selecionar todos',
    rescanBtn: 'Escanear Novamente',
    quickCleanLabel: 'Limpeza Rápida',
    spaceToFree: 'Espaço a liberar',
    cannotUndo: 'Esta ação não pode ser desfeita.',
    cacheCleanTitle: 'Limpeza de Cache de Apps',
    androidCacheNote: 'O Android 6+ não permite que apps limpem o cache de outros apps diretamente.\n\nAbriremos as configurações de cada app para limpeza manual.',
    selectedAppsCount: 'Apps selecionados',
    estimatedCacheLabel: 'Cache estimado',
    hibernateLimitNote: 'O Android não permite forçar a parada de outros apps sem permissões de sistema.\n\nAbriremos as configurações de cada app para parada manual.',
    ramToFree: 'RAM estimada a liberar',
    appsInBackground: 'apps em segundo plano',
    selectedLabel: 'selecionados',
    typeQuickLabel: 'Limpeza Rápida',
    typeAppLabel: 'Limpeza de Apps',
    typeApkLabel: 'APKs',
    openAndroidSettings: 'Abrir Configurações',
    itemsSelected: 'arquivo(s) selecionado(s)',
    storageUsed: 'Usado',
    storageFree: 'Livre',
    storageTotal: 'Total',
    scanAgainBtn: 'Escanear Novamente',
    allItems: 'Itens para limpar',
    advanced: 'Avançado',
    data: 'Dados',
    smartTrash: 'Lixeira Inteligente',
    disabled: 'Desativada',
    onlyAndroid: 'Disponível apenas no Android',
    released: 'Liberados',
    cleanups: 'Limpezas',
    filesLabel: 'Arquivos',
  },

  en: {
    tabHome: 'Home',
    tabTools: 'Tools',
    tabDiscover: 'Discover',
    tabProfile: 'Me',
    appName: 'MaxClean',
    junkFound: 'JUNK FOUND',
    scanComplete: 'Scan complete',
    scanning: 'Scanning...',
    quickClean: 'QUICK CLEAN',
    storage: 'Storage',
    ram: 'RAM',
    temperature: 'Temperature',
    battery: 'Battery',
    cpu: 'CPU',
    tools: 'Tools',
    seeAll: 'See all',
    free: 'Free',
    used: 'Used',
    total: 'Total',
    remaining: 'Remaining',
    scanNow: 'Scan Now',
    lastScan: 'Last scan',
    never: 'Never',
    smartClean: 'Smart Clean',
    totalFound: 'Total found',
    selected: 'Selected',
    itemsToClean: 'Items to clean',
    junkCache: 'Junk cache',
    tempFiles: 'Temp files',
    oldLogs: 'Old logs',
    appResiduals: 'App residuals',
    thumbnails: 'Thumbnails',
    emptyFolders: 'Empty folders',
    oldApks: 'Old APKs',
    uselessDownloads: 'Useless downloads',
    cleanBtn: 'CLEAN',
    cleanConfirm: 'Confirm Clean',
    cleanConfirmMsg: 'Delete selected items? This cannot be undone.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    cleaning: 'Cleaning...',
    cleanDone: 'Clean Complete!',
    spaceFreed: 'Space freed',
    filesRemoved: 'Files removed',
    timeTaken: 'Time taken',
    seconds: 's',
    appClean: 'App Clean',
    all: 'All',
    recommended: 'Recommended',
    large: 'Large',
    socialNets: 'Social',
    cleanApp: 'Clean cache and temp files',
    openSettings: 'Open App Settings',
    openSettingsNote: 'Android restricts clearing other apps\' cache. Tap to open app settings and clear manually.',
    appCleanBtn: 'CLEAN',
    duplicates: 'Duplicates',
    photos: 'Photos',
    videos: 'Videos',
    music: 'Music',
    docs: 'Docs',
    others: 'Others',
    duplicatesFound: 'Duplicates found',
    remove: 'REMOVE',
    largeFiles: 'Large Files',
    above: 'Above',
    deleteSelected: 'Delete Selected',
    downloads: 'Downloads',
    apks: 'APK',
    zips: 'ZIP',
    pdfs: 'PDF',
    neverUsed: 'Never used',
    emptyFoldersTitle: 'Empty Folders',
    foldersFound: 'empty folders found',
    deleteAll: 'DELETE ALL',
    totalSize: 'Total size',
    items: 'items',
    apkScanner: 'APK Scanner',
    version: 'Version',
    date: 'Date',
    location: 'Location',
    invalid: 'Invalid',
    duplicate: 'Duplicate',
    monitor: 'System Monitor',
    heaviestApps: 'Heaviest apps',
    memUsage: 'Memory usage',
    cpuUsage: 'CPU usage',
    battRemaining: 'Battery remaining',
    hibernate: 'Hibernate Apps',
    background: 'Background',
    autoStart: 'Auto start',
    consumingResources: 'apps consuming resources',
    blockSave: 'Block to save battery and RAM',
    hibernateBtn: 'HIBERNATE',
    highCpu: 'High CPU usage',
    highRam: 'High RAM usage',
    highBattery: 'High battery usage',
    runningBg: 'Running in background',
    history: 'Clean History',
    noHistory: 'No cleanups yet',
    noHistoryDesc: 'Run a cleanup to see history here',
    settings: 'Settings',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    language: 'Language',
    autoClean: 'Auto Clean',
    schedule: 'Schedule',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    notifications: 'Notifications',
    enableNotifications: 'Enable Notifications',
    trashDays: 'Delete trash after',
    days7: '7 days',
    days15: '15 days',
    days30: '30 days',
    about: 'About',
    privacy: 'Privacy Policy',
    terms: 'Terms of Use',
    share: 'Share App',
    rate: 'Rate on Store',
    clearHistory: 'Clear History',
    resetSettings: 'Reset Settings',
    safeDelete: 'Secure Delete',
    safeDeleteDesc: 'Overwrite files before deleting',
    permTitle: 'Permission Required',
    permStorage: 'MaxClean needs storage access to scan and clean files.',
    permGrant: 'Grant Permission',
    permDenied: 'Permission denied. Go to settings to enable.',
    errorScan: 'Scan error. Check permissions.',
    errorDelete: 'Error deleting file.',
    noFiles: 'No files found',
    noFilesDesc: 'Your device is clean!',
    limitationTitle: 'Android Limitation',
    limitationCache: 'Android 6+ does not allow apps to clear other apps\' cache directly. We\'ll open settings for manual clearing.',
    limitationSystem: 'System files cannot be accessed without special permissions.',

    // Additional UI strings
    chargeStatus: 'Charging',
    cpuTempLabel: 'CPU Temperature',
    zipFiles: 'ZIP Archives',
    deselectAll: 'Deselect all',
    selectAll: 'Select all',
    rescanBtn: 'Scan Again',
    quickCleanLabel: 'Quick Clean',
    spaceToFree: 'Space to free',
    cannotUndo: 'This action cannot be undone.',
    cacheCleanTitle: 'App Cache Clean',
    androidCacheNote: 'Android 6+ does not allow apps to clear other apps\' cache directly.\n\nWe\'ll open settings for each selected app for manual clearing.',
    selectedAppsCount: 'Selected apps',
    estimatedCacheLabel: 'Estimated cache',
    hibernateLimitNote: 'Android does not allow force-stopping other apps without system permissions.\n\nWe\'ll open settings for each app for manual force stop.',
    ramToFree: 'Estimated RAM to free',
    appsInBackground: 'apps in background',
    selectedLabel: 'selected',
    typeQuickLabel: 'Quick Clean',
    typeAppLabel: 'App Clean',
    typeApkLabel: 'APKs',
    openAndroidSettings: 'Open Settings',
    itemsSelected: 'file(s) selected',
    storageUsed: 'Used',
    storageFree: 'Free',
    storageTotal: 'Total',
    scanAgainBtn: 'Scan Again',
    allItems: 'Items to clean',
    advanced: 'Advanced',
    data: 'Data',
    smartTrash: 'Smart Trash',
    disabled: 'Disabled',
    onlyAndroid: 'Available on Android only',
    released: 'Released',
    cleanups: 'Cleanups',
    filesLabel: 'Files',
  },

  es: {
    tabHome: 'Inicio',
    tabTools: 'Herramientas',
    tabDiscover: 'Descubrir',
    tabProfile: 'Yo',
    appName: 'MaxClean',
    junkFound: 'BASURA ENCONTRADA',
    scanComplete: 'Análisis completado',
    scanning: 'Analizando...',
    quickClean: 'LIMPIEZA RÁPIDA',
    storage: 'Almacenamiento',
    ram: 'RAM',
    temperature: 'Temperatura',
    battery: 'Batería',
    cpu: 'CPU',
    tools: 'Herramientas',
    seeAll: 'Ver todas',
    free: 'Libre',
    used: 'Usado',
    total: 'Total',
    remaining: 'Restante',
    scanNow: 'Analizar Ahora',
    lastScan: 'Último análisis',
    never: 'Nunca',
    smartClean: 'Limpieza Inteligente',
    totalFound: 'Total encontrado',
    selected: 'Seleccionado',
    itemsToClean: 'Elementos a limpiar',
    junkCache: 'Caché inútil',
    tempFiles: 'Archivos temporales',
    oldLogs: 'Registros antiguos',
    appResiduals: 'Residuos de apps',
    thumbnails: 'Miniaturas',
    emptyFolders: 'Carpetas vacías',
    oldApks: 'APK antiguos',
    uselessDownloads: 'Descargas inútiles',
    cleanBtn: 'LIMPIAR',
    cleanConfirm: 'Confirmar Limpieza',
    cleanConfirmMsg: '¿Eliminar los elementos seleccionados? Esta acción no se puede deshacer.',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    cleaning: 'Limpiando...',
    cleanDone: '¡Limpieza Completa!',
    spaceFreed: 'Espacio liberado',
    filesRemoved: 'Archivos eliminados',
    timeTaken: 'Tiempo empleado',
    seconds: 's',
    appClean: 'Limpieza de Apps',
    all: 'Todos',
    recommended: 'Recomendado',
    large: 'Grandes',
    socialNets: 'Redes Sociales',
    cleanApp: 'Limpiar caché y archivos temporales',
    openSettings: 'Abrir Config. de la App',
    openSettingsNote: 'Android restringe la limpieza de caché de otras apps. Toca para abrir la configuración y limpiar manualmente.',
    appCleanBtn: 'LIMPIAR',
    duplicates: 'Duplicados',
    photos: 'Fotos',
    videos: 'Vídeos',
    music: 'Música',
    docs: 'Docs',
    others: 'Otros',
    duplicatesFound: 'Duplicados encontrados',
    remove: 'ELIMINAR',
    largeFiles: 'Archivos Grandes',
    above: 'Más de',
    deleteSelected: 'Eliminar Seleccionados',
    downloads: 'Descargas',
    apks: 'APK',
    zips: 'ZIP',
    pdfs: 'PDF',
    neverUsed: 'Nunca utilizados',
    emptyFoldersTitle: 'Carpetas Vacías',
    foldersFound: 'carpetas vacías encontradas',
    deleteAll: 'ELIMINAR TODO',
    totalSize: 'Tamaño total',
    items: 'elementos',
    apkScanner: 'Escáner de APK',
    version: 'Versión',
    date: 'Fecha',
    location: 'Ubicación',
    invalid: 'Inválido',
    duplicate: 'Duplicado',
    monitor: 'Monitor del Sistema',
    heaviestApps: 'Apps más pesadas',
    memUsage: 'Uso de memoria',
    cpuUsage: 'Uso de CPU',
    battRemaining: 'Batería restante',
    hibernate: 'Hibernar Apps',
    background: 'Segundo plano',
    autoStart: 'Inicio automático',
    consumingResources: 'apps consumiendo recursos',
    blockSave: 'Bloquear para ahorrar batería y RAM',
    hibernateBtn: 'HIBERNAR',
    highCpu: 'Alto consumo de CPU',
    highRam: 'Alto consumo de RAM',
    highBattery: 'Alto consumo de batería',
    runningBg: 'Ejecutando en segundo plano',
    history: 'Historial de Limpiezas',
    noHistory: 'Sin limpiezas aún',
    noHistoryDesc: 'Realiza una limpieza para ver el historial aquí',
    settings: 'Configuración',
    appearance: 'Apariencia',
    darkMode: 'Modo Oscuro',
    language: 'Idioma',
    autoClean: 'Limpieza Automática',
    schedule: 'Programación',
    daily: 'Diaria',
    weekly: 'Semanal',
    monthly: 'Mensual',
    notifications: 'Notificaciones',
    enableNotifications: 'Activar Notificaciones',
    trashDays: 'Vaciar papelera tras',
    days7: '7 días',
    days15: '15 días',
    days30: '30 días',
    about: 'Acerca de',
    privacy: 'Política de Privacidad',
    terms: 'Términos de Uso',
    share: 'Compartir App',
    rate: 'Valorar en la Tienda',
    clearHistory: 'Limpiar Historial',
    resetSettings: 'Restablecer Configuración',
    safeDelete: 'Eliminación Segura',
    safeDeleteDesc: 'Sobrescribir archivos antes de eliminar',
    permTitle: 'Permiso Necesario',
    permStorage: 'MaxClean necesita acceso al almacenamiento para analizar y limpiar archivos.',
    permGrant: 'Conceder Permiso',
    permDenied: 'Permiso denegado. Ve a configuración para activarlo.',
    errorScan: 'Error al analizar. Verifica los permisos.',
    errorDelete: 'Error al eliminar archivo.',
    noFiles: 'No se encontraron archivos',
    noFilesDesc: '¡Tu dispositivo está limpio!',
    limitationTitle: 'Limitación de Android',
    limitationCache: 'Android 6+ no permite que las apps limpien la caché de otras apps directamente. Abriremos la configuración para limpiar manualmente.',
    limitationSystem: 'Los archivos del sistema no son accesibles sin permisos especiales.',

    // Additional UI strings
    chargeStatus: 'Cargando',
    cpuTempLabel: 'Temperatura de la CPU',
    zipFiles: 'Archivos ZIP',
    deselectAll: 'Deseleccionar todo',
    selectAll: 'Seleccionar todo',
    rescanBtn: 'Analizar de nuevo',
    quickCleanLabel: 'Limpieza Rápida',
    spaceToFree: 'Espacio a liberar',
    cannotUndo: 'Esta acción no se puede deshacer.',
    cacheCleanTitle: 'Limpieza de Caché de Apps',
    androidCacheNote: 'Android 6+ no permite que las apps limpien la caché de otras apps directamente.\n\nAbriremos la configuración de cada app seleccionada para limpieza manual.',
    selectedAppsCount: 'Apps seleccionadas',
    estimatedCacheLabel: 'Caché estimada',
    hibernateLimitNote: 'Android no permite forzar el cierre de otras apps sin permisos del sistema.\n\nAbriremos la configuración de cada app para cierre manual.',
    ramToFree: 'RAM estimada a liberar',
    appsInBackground: 'apps en segundo plano',
    selectedLabel: 'seleccionados',
    typeQuickLabel: 'Limpieza Rápida',
    typeAppLabel: 'Limpieza de Apps',
    typeApkLabel: 'APKs',
    openAndroidSettings: 'Abrir Configuración',
    itemsSelected: 'archivo(s) seleccionado(s)',
    storageUsed: 'Usado',
    storageFree: 'Libre',
    storageTotal: 'Total',
    scanAgainBtn: 'Analizar de nuevo',
    allItems: 'Elementos a limpiar',
    advanced: 'Avanzado',
    data: 'Datos',
    smartTrash: 'Papelera Inteligente',
    disabled: 'Desactivada',
    onlyAndroid: 'Disponible solo en Android',
    released: 'Liberados',
    cleanups: 'Limpiezas',
    filesLabel: 'Archivos',
  },
};

export type StringKey = keyof typeof strings.pt;
